### PR TITLE
Make Kallisto RNA-seq example portable

### PR DESCRIPTION
**Pull request by tetron**
* Download and index steps are conditional on inputs
* Add Docker image for curl to be used in download steps
* Add NetworkAccess: true for download steps
* Add RAM requirements to kallisto steps

### CODE REVIEW

**Comment by mw55309** [comment]
Thank you!

**Comment by mw55309** [comment]
The one thing I would say about this is that v1.2 is not a valid version for my cwl-runner binary:

```
The CWL reference runner no longer supports pre CWL v1.0 documents. Supported versions are:
v1.0
v1.1
v1.1.0-dev1 (with --enable-dev flag only)
v1.2.0-dev1 (with --enable-dev flag only)
```

**Comment by mw55309** [comment]
Actually might be worth adding which version of cwltool or cwl-runner this will work with - it __doesn't__ work with 

```
$ cwl-runner --version
/usr/bin/cwl-runner 2.0.20200224214940
```


```
$ cwl-runner --enable-dev workflow.cwl inputs.yaml
INFO /usr/bin/cwl-runner 2.0.20200224214940
INFO Resolved 'workflow.cwl' to 'file:///home/ubuntu/cwl_rna_seq/workflow.cwl'
ERROR Tool definition failed validation:
workflow.cwl:3:1:   Object `workflow.cwl` is not valid because
                     tried `Workflow` but
workflow.cwl:62:1:     * the `outputs` field is not valid because
workflow.cwl:68:3:       item is invalid because
workflow.cwl:71:5:         the `pickValue` field is not valid because
                             tried PickValueMethod but
                               the value 'the_only_non_null' is not a valid PickValueMethod,
                               expected one of 'first_non_null', 'only_non_null', 'all_non_null'
workflow.cwl:20:1:     * the `steps` field is not valid because
                         tried array of <WorkflowStep> but
workflow.cwl:30:3:         item is invalid because
workflow.cwl:32:5:           the `in` field is not valid because
workflow.cwl:33:7:             item is invalid because
workflow.cwl:35:9:               the `pickValue` field is not valid because
                                   tried PickValueMethod but
                                     the value 'the_only_non_null' is not a valid PickValueMethod,
                                     expected one of 'first_non_null', 'only_non_null', 'all_non_null'
```

@tetron

**Comment by tetron** [comment]
You're using an old version of cwltool.  Where are you getting it from?  Could you install the latest version in a virtualenv?

**Pull request merged**
